package pojos;
// Generated 11-may-2019 16:07:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ModContador generated by hbm2java
 */
public class ModContador  implements java.io.Serializable {


     private int contadorId;
     private int valor;
     private Set bombas = new HashSet(0);

    public ModContador() {
    }

	
    public ModContador(int contadorId, int valor) {
        this.contadorId = contadorId;
        this.valor = valor;
    }
    public ModContador(int contadorId, int valor, Set bombas) {
       this.contadorId = contadorId;
       this.valor = valor;
       this.bombas = bombas;
    }
   
    public int getContadorId() {
        return this.contadorId;
    }
    
    public void setContadorId(int contadorId) {
        this.contadorId = contadorId;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }
    public Set getBombas() {
        return this.bombas;
    }
    
    public void setBombas(Set bombas) {
        this.bombas = bombas;
    }




}


