package pojos;
// Generated 11-may-2019 16:07:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ModPassword generated by hbm2java
 */
public class ModPassword  implements java.io.Serializable {


     private int passwordId;
     private String texto;
     private Set bombas = new HashSet(0);

    public ModPassword() {
    }

	
    public ModPassword(int passwordId, String texto) {
        this.passwordId = passwordId;
        this.texto = texto;
    }
    public ModPassword(int passwordId, String texto, Set bombas) {
       this.passwordId = passwordId;
       this.texto = texto;
       this.bombas = bombas;
    }
   
    public int getPasswordId() {
        return this.passwordId;
    }
    
    public void setPasswordId(int passwordId) {
        this.passwordId = passwordId;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Set getBombas() {
        return this.bombas;
    }
    
    public void setBombas(Set bombas) {
        this.bombas = bombas;
    }




}


