package pojos;
// Generated 11-may-2019 16:07:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ModSimon generated by hbm2java
 */
public class ModSimon  implements java.io.Serializable {


     private int simonId;
     private String secuencia;
     private Set bombas = new HashSet(0);

    public ModSimon() {
    }

	
    public ModSimon(int simonId, String secuencia) {
        this.simonId = simonId;
        this.secuencia = secuencia;
    }
    public ModSimon(int simonId, String secuencia, Set bombas) {
       this.simonId = simonId;
       this.secuencia = secuencia;
       this.bombas = bombas;
    }
   
    public int getSimonId() {
        return this.simonId;
    }
    
    public void setSimonId(int simonId) {
        this.simonId = simonId;
    }
    public String getSecuencia() {
        return this.secuencia;
    }
    
    public void setSecuencia(String secuencia) {
        this.secuencia = secuencia;
    }
    public Set getBombas() {
        return this.bombas;
    }
    
    public void setBombas(Set bombas) {
        this.bombas = bombas;
    }




}


