package pojos;
// Generated 11-may-2019 16:07:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ModSimbolos generated by hbm2java
 */
public class ModSimbolos  implements java.io.Serializable {


     private int simboloId;
     private String simbolo;
     private Set bombas = new HashSet(0);

    public ModSimbolos() {
    }

	
    public ModSimbolos(int simboloId, String simbolo) {
        this.simboloId = simboloId;
        this.simbolo = simbolo;
    }
    public ModSimbolos(int simboloId, String simbolo, Set bombas) {
       this.simboloId = simboloId;
       this.simbolo = simbolo;
       this.bombas = bombas;
    }
   
    public int getSimboloId() {
        return this.simboloId;
    }
    
    public void setSimboloId(int simboloId) {
        this.simboloId = simboloId;
    }
    public String getSimbolo() {
        return this.simbolo;
    }
    
    public void setSimbolo(String simbolo) {
        this.simbolo = simbolo;
    }
    public Set getBombas() {
        return this.bombas;
    }
    
    public void setBombas(Set bombas) {
        this.bombas = bombas;
    }




}


