package pojos;
// Generated 11-may-2019 16:07:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ModTemporizador generated by hbm2java
 */
public class ModTemporizador  implements java.io.Serializable {


     private int tempoId;
     private int valor;
     private Set bombas = new HashSet(0);

    public ModTemporizador() {
    }

	
    public ModTemporizador(int tempoId, int valor) {
        this.tempoId = tempoId;
        this.valor = valor;
    }
    public ModTemporizador(int tempoId, int valor, Set bombas) {
       this.tempoId = tempoId;
       this.valor = valor;
       this.bombas = bombas;
    }
   
    public int getTempoId() {
        return this.tempoId;
    }
    
    public void setTempoId(int tempoId) {
        this.tempoId = tempoId;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }
    public Set getBombas() {
        return this.bombas;
    }
    
    public void setBombas(Set bombas) {
        this.bombas = bombas;
    }




}


